/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const JuknisLazyImport = createFileRoute('/juknis')()

// Create/Update Routes

const JuknisLazyRoute = JuknisLazyImport.update({
  id: '/juknis',
  path: '/juknis',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/juknis.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/juknis': {
      id: '/juknis'
      path: '/juknis'
      fullPath: '/juknis'
      preLoaderRoute: typeof JuknisLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/juknis': typeof JuknisLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/juknis': typeof JuknisLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/juknis': typeof JuknisLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/juknis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/juknis'
  id: '__root__' | '/' | '/juknis'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JuknisLazyRoute: typeof JuknisLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JuknisLazyRoute: JuknisLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/juknis"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/juknis": {
      "filePath": "juknis.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
